language: node_js
dist: trusty
sudo: true
node_js:
- 8
addons:
  apt:
    packages:
    - python-pip
notifications:
  email: false
  slack:
    rooms:
    - gapminder:siB4Z9ymsYR6qHnRPpgUoB2Q#vizabi-spam
    on_success: change
    on_failure: always
cache:
  directories:
  - node_modules
before_install:
- ssh-keyscan -H $TOOLSPAGE_HOST 2>&1 | tee -a $HOME/.ssh/known_hosts
- openssl aes-256-cbc -K $encrypted_02a74dd532b3_key -iv $encrypted_02a74dd532b3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- npm install -g npm@latest
- sudo pip install s3cmd
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm run build
script:
- npm run deploy
deploy:
- provider: npm
  skip_cleanup: true
  email: konzeptmeister@gmail.com
  api_key:
    secure: NwgxH591kbawDf4zu+I2qVpu4zj5RyIbl6IdWMf4EnEARaEfVGU/cFsYinWJSamRODHVt+zN6Zij5QkPulpGS2q11ncReNKd6f93SFam9MHJtkBvUCgzFzq0KIfr8S2tDG/KrAIMWVzusf5n95QfzdkgNHB25D9ZNfydsI0zLUcXzLGLwDpBAjXc/Md86RuvqX+dA6jocw64M4oz/+IowK+CqaypIOY/G8LRHgNi2sz9tYB9P03kiWNZR+qwv9nj/Ew/Svdyd2HYF3/4EiFhMkrZJFnccJZGNmJzG9WcHqKqDwrouWU7ApZRDJj1kvZPOeGDiTKI/STA0tccnltpzjblnjWYAB4PkPZ912jOxKSOXeXU2cE8kKZrKfd/zefVsXz7gL9Gct7CixXS+BDSvRuCGRWmbYwdgQKcJ3bb1P28mcz67a3EcwjWRIXjXFRC+p4uLdGziqnTJYnDt8qsxEwAfz2UpYmf6DkHm4lTYCwAJ2lATKRg04S7BABLYCvruuuPkaOreFP0tGOzHI2JOs8qYy9Qp/soz5zTnoqV0ewunt2ZG/4RZeT/ABWsNt/ui2vrrc4Dn7kWdYqXh2un4E0ZqGcFvBGusnds3AhPmn0KznA+gXhPPvG3zoKj0r/TFseGjDSNqj6/tn2bcqvV/SBb9vGqBaDjuSFT0diMI/w=
  on:
    branch: develop
    node: 8
    condition: "-e /tmp/deployment.flag"
- provider: script
  skip_cleanup: true
  script: ssh $TOOLSPAGE_USER@$TOOLSPAGE_HOST 'sh /home/root/redeploy.sh "$TRAVIS_REPO_SLUG"'
  on:
    branch: develop
